#!/usr/bin/env bash
# A bash script that configures the ubuntu server with the below requirerments
# Requirements:
# Local host resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
# The checker is running on docker

cp etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8 facebook.com" > ~/hosts.new
cp -f ~/hosts.new etc/hosts
